/**
 * Art Generation Prompts - High-res styles for AI generation
 * Terrain/World: Medieval fantasy top-down painterly
 * Characters: Anime/JRPG portrait style
 * Effects: Stylized VFX
 */

export interface ArtPrompt {
  id: string;
  category: 'terrain' | 'decor' | 'city' | 'character' | 'effect' | 'item' | 'mount' | 'enemy';
  name: string;
  description: string;
  style: 'medieval-topdown' | 'anime-portrait' | 'anime-chibi' | 'pixel-icon' | 'vfx-painterly';
  size: { width: number; height: number };
  prompt: string;
  negativePrompt?: string;
  variants?: string[];
  tags: string[];
}

// === STYLE GUIDES ===
const STYLE = {
  medievalTopdown: 'hand-painted medieval fantasy, top-down orthographic view, rich earthy tones, soft shadows, painterly texture, game asset, seamless tileable',
  animePortrait: 'anime illustration, JRPG character art, dramatic lighting, detailed face and eyes, upper body portrait, vibrant colors, high detail, professional quality, artstation',
  animeChibi: 'chibi anime style, cute proportions, full body, simple clean lines, soft shading, game sprite, transparent background',
  pixelIcon: 'pixel art icon, 16-bit style, clean readable silhouette, limited palette, game UI element',
  vfxPainterly: 'magical VFX, painterly style, glowing particles, ethereal energy, transparent background, game effect sprite',
};

const NEGATIVE = {
  character: 'blurry, low quality, deformed, ugly, bad anatomy, extra limbs, text, watermark, signature, frame, border',
  terrain: 'blurry, noisy, artifacts, text, watermark, perspective distortion, 3D render',
  effect: 'blurry, low quality, solid background, text, watermark',
};

export const ART_PROMPTS: ArtPrompt[] = [
  // ============================================
  // TERRAIN TILES (256x256 seamless)
  // ============================================
  {
    id: 'terrain_grass',
    category: 'terrain',
    name: 'Grassland',
    description: 'Lush green meadow with wildflowers and clovers',
    style: 'medieval-topdown',
    size: { width: 256, height: 256 },
    prompt: `${STYLE.medievalTopdown}, lush grass meadow floor, scattered tiny wildflowers in yellow and white, small clovers, dappled sunlight, vibrant greens with golden highlights`,
    negativePrompt: NEGATIVE.terrain,
    variants: ['spring meadow with butterflies', 'autumn grass with fallen leaves', 'wet dewy morning grass'],
    tags: ['biome', 'safe', 'starting-area'],
  },
  {
    id: 'terrain_forest',
    category: 'terrain',
    name: 'Dense Forest',
    description: 'Dark forest floor with fallen leaves and moss',
    style: 'medieval-topdown',
    size: { width: 256, height: 256 },
    prompt: `${STYLE.medievalTopdown}, dark forest floor, fallen autumn leaves in browns and oranges, patches of green moss, twisted roots, dappled shadows through canopy, mysterious atmosphere`,
    negativePrompt: NEGATIVE.terrain,
    variants: ['enchanted glowing forest', 'dead haunted forest', 'ancient primeval forest'],
    tags: ['biome', 'danger', 'exploration'],
  },
  {
    id: 'terrain_mountain',
    category: 'terrain',
    name: 'Rocky Mountain',
    description: 'Grey stone and gravel mountain terrain',
    style: 'medieval-topdown',
    size: { width: 256, height: 256 },
    prompt: `${STYLE.medievalTopdown}, rocky mountain terrain, grey and brown stones, scattered gravel, small cracks and crevices, sparse hardy vegetation, rugged texture`,
    negativePrompt: NEGATIVE.terrain,
    variants: ['volcanic black rock', 'crystal-studded cavern floor', 'ancient ruins stone'],
    tags: ['biome', 'difficult', 'mineral'],
  },
  {
    id: 'terrain_snow',
    category: 'terrain',
    name: 'Snowy Tundra',
    description: 'Pristine white snow with ice crystals',
    style: 'medieval-topdown',
    size: { width: 256, height: 256 },
    prompt: `${STYLE.medievalTopdown}, pristine white snow, subtle blue shadows, sparkling ice crystals, wind-blown powder texture, frozen and serene, winter atmosphere`,
    negativePrompt: NEGATIVE.terrain,
    variants: ['deep blizzard snow', 'melting spring snow', 'magical aurora-lit snow'],
    tags: ['biome', 'cold', 'difficult'],
  },
  {
    id: 'terrain_shore',
    category: 'terrain',
    name: 'Sandy Shore',
    description: 'Golden beach sand with shells and pebbles',
    style: 'medieval-topdown',
    size: { width: 256, height: 256 },
    prompt: `${STYLE.medievalTopdown}, golden beach sand, scattered seashells and smooth pebbles, tide marks, warm sunlit texture, coastal atmosphere`,
    negativePrompt: NEGATIVE.terrain,
    variants: ['tropical white sand', 'rocky tide pools', 'stormy grey beach'],
    tags: ['biome', 'coastal', 'transition'],
  },
  {
    id: 'terrain_river',
    category: 'terrain',
    name: 'Shallow River',
    description: 'Clear flowing water with visible riverbed',
    style: 'medieval-topdown',
    size: { width: 256, height: 256 },
    prompt: `${STYLE.medievalTopdown}, clear shallow river water, visible smooth stones on riverbed, gentle ripples and caustics, turquoise and blue tones, sparkling sunlight reflections`,
    negativePrompt: NEGATIVE.terrain,
    variants: ['rushing rapids', 'frozen ice river', 'magical glowing stream'],
    tags: ['biome', 'water', 'obstacle'],
  },
  {
    id: 'terrain_sea',
    category: 'terrain',
    name: 'Deep Ocean',
    description: 'Dark blue deep sea water',
    style: 'medieval-topdown',
    size: { width: 256, height: 256 },
    prompt: `${STYLE.medievalTopdown}, deep ocean water, dark navy blue with subtle wave patterns, foam highlights, mysterious depths, ambient light from above`,
    negativePrompt: NEGATIVE.terrain,
    variants: ['stormy rough seas', 'calm tropical lagoon', 'bioluminescent night ocean'],
    tags: ['biome', 'water', 'impassable'],
  },
  {
    id: 'terrain_swamp',
    category: 'terrain',
    name: 'Murky Swamp',
    description: 'Stagnant water with algae and mud',
    style: 'medieval-topdown',
    size: { width: 256, height: 256 },
    prompt: `${STYLE.medievalTopdown}, murky swamp water, dark green stagnant pools, floating algae and duckweed, muddy patches, eerie mist, toxic atmosphere`,
    negativePrompt: NEGATIVE.terrain,
    variants: ['poisonous purple swamp', 'ancient bog with bones', 'magical fairy swamp'],
    tags: ['biome', 'danger', 'slow'],
  },
  {
    id: 'terrain_lowland',
    category: 'terrain',
    name: 'Dirt Path',
    description: 'Well-worn earth road with dried grass',
    style: 'medieval-topdown',
    size: { width: 256, height: 256 },
    prompt: `${STYLE.medievalTopdown}, worn dirt path, brown earth with cart wheel tracks, patches of dried yellow grass, small stones, dusty texture, traveled road`,
    negativePrompt: NEGATIVE.terrain,
    variants: ['muddy rain-soaked path', 'ancient trade route', 'overgrown abandoned road'],
    tags: ['biome', 'safe', 'travel'],
  },
  {
    id: 'terrain_town',
    category: 'terrain',
    name: 'Cobblestone Street',
    description: 'Medieval town cobblestone pavement',
    style: 'medieval-topdown',
    size: { width: 256, height: 256 },
    prompt: `${STYLE.medievalTopdown}, medieval cobblestone street, grey and brown fitted stones, moss growing between cracks, worn smooth surfaces, torch-lit atmosphere`,
    negativePrompt: NEGATIVE.terrain,
    variants: ['market square with stains', 'noble district marble', 'ancient dwarven stonework'],
    tags: ['biome', 'safe', 'civilization'],
  },

  // ============================================
  // DECOR OBJECTS (64-128px transparent)
  // ============================================
  {
    id: 'decor_tree_oak',
    category: 'decor',
    name: 'Oak Tree',
    description: 'Majestic deciduous oak tree canopy',
    style: 'medieval-topdown',
    size: { width: 128, height: 128 },
    prompt: `${STYLE.medievalTopdown}, oak tree top-down view, lush green circular canopy, varied leaf clusters, dappled shadows, transparent background`,
    negativePrompt: NEGATIVE.terrain,
    variants: ['ancient giant oak', 'autumn red oak', 'spring blossoming oak'],
    tags: ['nature', 'obstacle', 'shade'],
  },
  {
    id: 'decor_tree_pine',
    category: 'decor',
    name: 'Pine Tree',
    description: 'Tall conifer pine tree',
    style: 'medieval-topdown',
    size: { width: 128, height: 128 },
    prompt: `${STYLE.medievalTopdown}, pine tree top-down view, dark green conifer needles, triangular shape from above, slight shadow, transparent background`,
    negativePrompt: NEGATIVE.terrain,
    variants: ['snow-laden pine', 'dead brown pine', 'magical glowing pine'],
    tags: ['nature', 'obstacle', 'forest'],
  },
  {
    id: 'decor_ruins',
    category: 'decor',
    name: 'Ancient Ruins',
    description: 'Crumbling stone walls and pillars',
    style: 'medieval-topdown',
    size: { width: 128, height: 128 },
    prompt: `${STYLE.medievalTopdown}, ancient stone ruins top-down view, crumbling walls and broken pillars, overgrown with vines, mysterious glyphs, transparent background`,
    negativePrompt: NEGATIVE.terrain,
    variants: ['elven crystal ruins', 'dwarven forge ruins', 'dark temple ruins'],
    tags: ['structure', 'exploration', 'lore'],
  },
  {
    id: 'decor_tree_dead',
    category: 'decor',
    name: 'Dead Tree',
    description: 'Withered leafless tree',
    style: 'medieval-topdown',
    size: { width: 128, height: 128 },
    prompt: `${STYLE.medievalTopdown}, dead tree top-down view, bare twisted branches, grey bark, haunting silhouette, transparent background`,
    negativePrompt: NEGATIVE.terrain,
    tags: ['nature', 'dark', 'obstacle'],
  },
  {
    id: 'decor_tree_palm',
    category: 'decor',
    name: 'Palm Tree',
    description: 'Tropical palm with fronds',
    style: 'medieval-topdown',
    size: { width: 128, height: 128 },
    prompt: `${STYLE.medievalTopdown}, palm tree top-down view, tropical green fronds radiating outward, coconuts, beach vibes, transparent background`,
    negativePrompt: NEGATIVE.terrain,
    tags: ['nature', 'tropical', 'obstacle'],
  },
  {
    id: 'decor_tree_frozen',
    category: 'decor',
    name: 'Frozen Tree',
    description: 'Ice-covered winter tree',
    style: 'medieval-topdown',
    size: { width: 128, height: 128 },
    prompt: `${STYLE.medievalTopdown}, frozen tree top-down view, branches covered in ice and snow, crystalline icicles, frost patterns, transparent background`,
    negativePrompt: NEGATIVE.terrain,
    tags: ['nature', 'cold', 'obstacle'],
  },
  {
    id: 'decor_rock_small',
    category: 'decor',
    name: 'Small Rock',
    description: 'Minor stone obstacle',
    style: 'medieval-topdown',
    size: { width: 64, height: 64 },
    prompt: `${STYLE.medievalTopdown}, small rock top-down view, grey stone with moss spots, natural weathered texture, transparent background`,
    negativePrompt: NEGATIVE.terrain,
    tags: ['nature', 'obstacle', 'common'],
  },
  {
    id: 'decor_rock_large',
    category: 'decor',
    name: 'Large Boulder',
    description: 'Major stone formation',
    style: 'medieval-topdown',
    size: { width: 96, height: 96 },
    prompt: `${STYLE.medievalTopdown}, large boulder top-down view, massive grey stone, moss and lichen covering, cast shadow, transparent background`,
    negativePrompt: NEGATIVE.terrain,
    tags: ['nature', 'obstacle', 'cover'],
  },
  {
    id: 'decor_bush',
    category: 'decor',
    name: 'Bush',
    description: 'Green shrub foliage',
    style: 'medieval-topdown',
    size: { width: 64, height: 64 },
    prompt: `${STYLE.medievalTopdown}, bush top-down view, dense green foliage, rounded shrub shape, varied leaf textures, transparent background`,
    negativePrompt: NEGATIVE.terrain,
    tags: ['nature', 'cover', 'common'],
  },
  {
    id: 'decor_flowers',
    category: 'decor',
    name: 'Flower Patch',
    description: 'Colorful wildflowers',
    style: 'medieval-topdown',
    size: { width: 64, height: 64 },
    prompt: `${STYLE.medievalTopdown}, flower patch top-down view, colorful wildflowers in pink yellow and purple, green stems, scattered natural arrangement, transparent background`,
    negativePrompt: NEGATIVE.terrain,
    tags: ['nature', 'decorative', 'pretty'],
  },
  {
    id: 'decor_mushrooms',
    category: 'decor',
    name: 'Mushroom Cluster',
    description: 'Fantasy toadstools',
    style: 'medieval-topdown',
    size: { width: 64, height: 64 },
    prompt: `${STYLE.medievalTopdown}, mushroom cluster top-down view, red spotted caps, fantasy toadstools, varied sizes, magical glow, transparent background`,
    negativePrompt: NEGATIVE.terrain,
    variants: ['glowing magic mushrooms', 'poisonous purple mushrooms'],
    tags: ['nature', 'magical', 'alchemy'],
  },
  {
    id: 'decor_bones',
    category: 'decor',
    name: 'Bone Pile',
    description: 'Scattered skeletal remains',
    style: 'medieval-topdown',
    size: { width: 64, height: 64 },
    prompt: `${STYLE.medievalTopdown}, bone pile top-down view, scattered white bones and skull, ancient remains, weathered texture, transparent background`,
    negativePrompt: NEGATIVE.terrain,
    tags: ['dark', 'danger', 'lore'],
  },
  {
    id: 'decor_campfire',
    category: 'decor',
    name: 'Campfire',
    description: 'Burning fire with logs',
    style: 'medieval-topdown',
    size: { width: 96, height: 96 },
    prompt: `${STYLE.medievalTopdown}, campfire top-down view, burning orange flames, arranged logs, glowing embers, warm light circle, transparent background`,
    negativePrompt: NEGATIVE.terrain,
    tags: ['rest', 'light', 'warmth'],
  },
  {
    id: 'decor_tent',
    category: 'decor',
    name: 'Camp Tent',
    description: 'Medieval camping shelter',
    style: 'medieval-topdown',
    size: { width: 128, height: 128 },
    prompt: `${STYLE.medievalTopdown}, medieval tent top-down view, canvas shelter with peaked roof, guy ropes, adventurer camp style, transparent background`,
    negativePrompt: NEGATIVE.terrain,
    tags: ['structure', 'rest', 'camp'],
  },
  {
    id: 'decor_waterlily',
    category: 'decor',
    name: 'Water Lily',
    description: 'Floating lily pad with flower',
    style: 'medieval-topdown',
    size: { width: 64, height: 64 },
    prompt: `${STYLE.medievalTopdown}, water lily top-down view, green lily pad with pink flower, floating on water, serene, transparent background`,
    negativePrompt: NEGATIVE.terrain,
    tags: ['water', 'nature', 'pretty'],
  },
  {
    id: 'decor_reeds',
    category: 'decor',
    name: 'Reeds',
    description: 'Tall swamp grass',
    style: 'medieval-topdown',
    size: { width: 64, height: 64 },
    prompt: `${STYLE.medievalTopdown}, reeds top-down view, tall cattails and swamp grass, brown seed heads, clustered growth, transparent background`,
    negativePrompt: NEGATIVE.terrain,
    tags: ['water', 'swamp', 'nature'],
  },

  // ============================================
  // CITIES (512px detailed)
  // ============================================
  {
    id: 'city_medieval',
    category: 'city',
    name: 'Medieval Castle',
    description: 'Classic stone fortress with towers',
    style: 'medieval-topdown',
    size: { width: 512, height: 512 },
    prompt: `${STYLE.medievalTopdown}, medieval castle fortress, white stone walls with blue banners, four corner towers with pointed roofs, central keep, cobblestone courtyard, drawbridge over moat, highly detailed architecture`,
    negativePrompt: NEGATIVE.terrain,
    variants: ['ruined abandoned castle', 'grand royal palace', 'fortified war castle'],
    tags: ['settlement', 'human', 'military'],
  },
  {
    id: 'city_desert',
    category: 'city',
    name: 'Desert Oasis City',
    description: 'Sandstone domes and minarets',
    style: 'medieval-topdown',
    size: { width: 512, height: 512 },
    prompt: `${STYLE.medievalTopdown}, desert oasis city, golden sandstone buildings, white domed roofs, tall minarets, palm trees in courtyard, blue tile accents, arabian fantasy architecture`,
    negativePrompt: NEGATIVE.terrain,
    variants: ['ancient pyramid city', 'merchant bazaar city', 'sultan palace'],
    tags: ['settlement', 'trade', 'exotic'],
  },
  {
    id: 'city_asian',
    category: 'city',
    name: 'Eastern Temple',
    description: 'Pagoda complex with gardens',
    style: 'medieval-topdown',
    size: { width: 512, height: 512 },
    prompt: `${STYLE.medievalTopdown}, asian pagoda temple complex, red and gold tiered roofs, zen rock garden, cherry blossom trees, stone lanterns, wooden bridges over koi ponds, serene atmosphere`,
    negativePrompt: NEGATIVE.terrain,
    variants: ['warrior dojo', 'mountain monastery', 'imperial palace'],
    tags: ['settlement', 'spiritual', 'eastern'],
  },
  {
    id: 'city_nordic',
    category: 'city',
    name: 'Viking Settlement',
    description: 'Wooden longhouses and great hall',
    style: 'medieval-topdown',
    size: { width: 512, height: 512 },
    prompt: `${STYLE.medievalTopdown}, viking nordic village, wooden longhouses with turf roofs, great mead hall with dragon carvings, dock with longships, snow-covered pine trees, runic stones, northern lights`,
    negativePrompt: NEGATIVE.terrain,
    variants: ['frozen ice fortress', 'fishing village', 'warrior stronghold'],
    tags: ['settlement', 'warrior', 'northern'],
  },
  {
    id: 'city_elven',
    category: 'city',
    name: 'Elven Grove',
    description: 'Treehouse city in ancient forest',
    style: 'medieval-topdown',
    size: { width: 512, height: 512 },
    prompt: `${STYLE.medievalTopdown}, elven forest city, elegant treehouses connected by rope bridges, massive ancient trees, glowing mushrooms and fireflies, silver and green architecture, magical crystalline spires, ethereal atmosphere`,
    negativePrompt: NEGATIVE.terrain,
    variants: ['dark elf underground city', 'high elf crystal towers', 'wood elf hidden village'],
    tags: ['settlement', 'elven', 'magical'],
  },
  {
    id: 'city_dwarven',
    category: 'city',
    name: 'Dwarven Hold',
    description: 'Mountain fortress with forges',
    style: 'medieval-topdown',
    size: { width: 512, height: 512 },
    prompt: `${STYLE.medievalTopdown}, dwarven mountain hold entrance, massive stone carved gates, glowing forge fires, mine cart tracks, golden and copper accents, runic engravings, smoke from chimneys, industrial fantasy`,
    negativePrompt: NEGATIVE.terrain,
    variants: ['deep mine city', 'forge district', 'treasury vault'],
    tags: ['settlement', 'dwarven', 'industrial'],
  },

  // ============================================
  // CHARACTER PORTRAITS (512px anime style)
  // ============================================
  // STARTER CHARACTERS
  {
    id: 'char_samurai_portrait',
    category: 'character',
    name: 'Samurai',
    description: 'Honorable warrior of the eastern lands',
    style: 'anime-portrait',
    size: { width: 512, height: 512 },
    prompt: `${STYLE.animePortrait}, samurai warrior, traditional red and black yoroi armor with gold trim, katana resting on shoulder, dark hair in topknot, battle-scarred but noble face, cherry blossoms falling, determined expression, warm sunset lighting`,
    negativePrompt: NEGATIVE.character,
    variants: ['ronin wanderer', 'legendary shogun', 'shadow samurai'],
    tags: ['starter', 'melee', 'fire', 'eastern'],
  },
  {
    id: 'char_witch_portrait',
    category: 'character',
    name: 'Witch',
    description: 'Mysterious sorceress of ancient magic',
    style: 'anime-portrait',
    size: { width: 512, height: 512 },
    prompt: `${STYLE.animePortrait}, beautiful witch sorceress, flowing purple robes with silver star patterns, pointed witch hat with crescent moon, long silver-white hair, mystical purple eyes, magical orbs floating around her, mysterious knowing smile, moonlit night background`,
    negativePrompt: NEGATIVE.character,
    variants: ['coven leader', 'hedge witch', 'dark enchantress'],
    tags: ['starter', 'magic', 'arcane', 'female'],
  },
  {
    id: 'char_ninja_portrait',
    category: 'character',
    name: 'Ninja',
    description: 'Silent assassin from the shadows',
    style: 'anime-portrait',
    size: { width: 512, height: 512 },
    prompt: `${STYLE.animePortrait}, ninja assassin, black shinobi shozoku with red accents, face mask revealing only intense sharp eyes, short spiky black hair, kunai in hand, smoke and shadows swirling, crescent moon behind, deadly calm expression`,
    negativePrompt: NEGATIVE.character,
    variants: ['kunoichi female ninja', 'demon ninja', 'legendary shinobi'],
    tags: ['starter', 'speed', 'physical', 'stealth'],
  },
  {
    id: 'char_paladin_portrait',
    category: 'character',
    name: 'Paladin',
    description: 'Holy knight blessed by the gods',
    style: 'anime-portrait',
    size: { width: 512, height: 512 },
    prompt: `${STYLE.animePortrait}, holy paladin knight, ornate golden plate armor with white tabard and sun emblem, flowing blonde hair, kind but fierce blue eyes, radiant holy light emanating, divine halo effect, noble heroic pose, cathedral background`,
    negativePrompt: NEGATIVE.character,
    variants: ['crusader templar', 'fallen paladin', 'royal champion'],
    tags: ['starter', 'tank', 'light', 'holy'],
  },
  {
    id: 'char_necromancer_portrait',
    category: 'character',
    name: 'Necromancer',
    description: 'Master of death and undeath',
    style: 'anime-portrait',
    size: { width: 512, height: 512 },
    prompt: `${STYLE.animePortrait}, dark necromancer, tattered black robes with skull clasps, pale gaunt face with glowing purple eyes, bone staff with soul gem, ghostly spirits swirling around, graveyard mist, sinister but intelligent expression, green necrotic energy`,
    negativePrompt: NEGATIVE.character,
    variants: ['lich king', 'death priest', 'soul harvester'],
    tags: ['starter', 'summon', 'dark', 'undead'],
  },
  {
    id: 'char_bard_portrait',
    category: 'character',
    name: 'Bard',
    description: 'Charismatic performer and storyteller',
    style: 'anime-portrait',
    size: { width: 512, height: 512 },
    prompt: `${STYLE.animePortrait}, charming bard, colorful renaissance performer outfit in red and teal, feathered cap, ornate lute in hands, warm brown eyes with mischievous glint, confident smile, musical notes floating magically, tavern warm lighting`,
    negativePrompt: NEGATIVE.character,
    variants: ['war drummer', 'court jester', 'legendary skald'],
    tags: ['starter', 'support', 'sonic', 'charisma'],
  },
  {
    id: 'char_druid_portrait',
    category: 'character',
    name: 'Druid',
    description: 'Guardian of nature and wild magic',
    style: 'anime-portrait',
    size: { width: 512, height: 512 },
    prompt: `${STYLE.animePortrait}, nature druid, green and brown robes woven with living vines, antler headdress with flowers, wooden staff sprouting leaves, wise gentle eyes, earthy skin with bark-like patterns, forest animals gathering, ancient grove background`,
    negativePrompt: NEGATIVE.character,
    variants: ['moon druid', 'storm druid', 'corruption druid'],
    tags: ['starter', 'nature', 'shapeshifter', 'healing'],
  },

  // ELEMENTAL VARIANTS
  {
    id: 'char_fire_samurai_portrait',
    category: 'character',
    name: 'Fire Samurai',
    description: 'Warrior infused with flame spirit',
    style: 'anime-portrait',
    size: { width: 512, height: 512 },
    prompt: `${STYLE.animePortrait}, fire samurai, burning red armor wreathed in flames, katana blade of pure fire, wild flame-like red hair, blazing orange eyes, phoenix spirit behind, volcanic explosion background, intense furious expression`,
    negativePrompt: NEGATIVE.character,
    tags: ['elemental', 'fire', 'melee', 'damage'],
  },
  {
    id: 'char_ice_witch_portrait',
    category: 'character',
    name: 'Ice Witch',
    description: 'Sorceress of eternal winter',
    style: 'anime-portrait',
    size: { width: 512, height: 512 },
    prompt: `${STYLE.animePortrait}, ice witch, crystalline blue robes made of frost, crown of icicles, pale blue skin with frost patterns, piercing ice-blue eyes, frozen magic swirling, snowflakes in hair, glacier background, cold regal beauty`,
    negativePrompt: NEGATIVE.character,
    tags: ['elemental', 'ice', 'magic', 'control'],
  },
  {
    id: 'char_storm_ninja_portrait',
    category: 'character',
    name: 'Storm Ninja',
    description: 'Lightning-fast assassin',
    style: 'anime-portrait',
    size: { width: 512, height: 512 },
    prompt: `${STYLE.animePortrait}, storm ninja, electric blue and white outfit crackling with lightning, spiky white hair standing from static, glowing electric eyes, kunai made of lightning, storm clouds and lightning bolts, intense electric aura`,
    negativePrompt: NEGATIVE.character,
    tags: ['elemental', 'lightning', 'speed', 'damage'],
  },

  // MONSTER CHARACTERS
  {
    id: 'char_dragon_knight_portrait',
    category: 'character',
    name: 'Dragon Knight',
    description: 'Warrior bonded with dragon blood',
    style: 'anime-portrait',
    size: { width: 512, height: 512 },
    prompt: `${STYLE.animePortrait}, dragon knight, crimson draconic armor with scales and horns, dragon wing cape, reptilian golden eyes with slit pupils, fanged expression, dragon spirit manifesting behind, volcanic lair background, fierce and primal`,
    negativePrompt: NEGATIVE.character,
    tags: ['monster', 'dragon', 'melee', 'fire'],
  },
  {
    id: 'char_vampire_portrait',
    category: 'character',
    name: 'Vampire Lord',
    description: 'Ancient bloodthirsty noble',
    style: 'anime-portrait',
    size: { width: 512, height: 512 },
    prompt: `${STYLE.animePortrait}, elegant vampire lord, gothic black and crimson aristocratic attire with high collar, slicked back black hair, pale porcelain skin, glowing red eyes, visible fangs in subtle smile, blood magic swirling, gothic castle background`,
    negativePrompt: NEGATIVE.character,
    tags: ['monster', 'undead', 'lifesteal', 'dark'],
  },
  {
    id: 'char_angel_portrait',
    category: 'character',
    name: 'Divine Angel',
    description: 'Celestial warrior of light',
    style: 'anime-portrait',
    size: { width: 512, height: 512 },
    prompt: `${STYLE.animePortrait}, divine angel, radiant white feathered wings, golden armor with holy symbols, flowing white hair with golden halo, pure white eyes glowing with divine light, celestial sword, heavenly clouds and light rays background`,
    negativePrompt: NEGATIVE.character,
    tags: ['monster', 'holy', 'light', 'flying'],
  },
  {
    id: 'char_demon_portrait',
    category: 'character',
    name: 'Infernal Demon',
    description: 'Fiend from the burning hells',
    style: 'anime-portrait',
    size: { width: 512, height: 512 },
    prompt: `${STYLE.animePortrait}, infernal demon, dark red skin with glowing cracks, massive curved horns, burning yellow eyes, fanged menacing grin, bat-like wings, hellfire and brimstone aura, infernal chains, volcanic hell background`,
    negativePrompt: NEGATIVE.character,
    tags: ['monster', 'demon', 'fire', 'dark'],
  },

  // LEGENDARY CHARACTERS
  {
    id: 'char_phoenix_portrait',
    category: 'character',
    name: 'Phoenix',
    description: 'Immortal bird of rebirth',
    style: 'anime-portrait',
    size: { width: 512, height: 512 },
    prompt: `${STYLE.animePortrait}, phoenix humanoid, body made of golden and red flames, feathered fire wings, blazing crown of feathers, eyes of pure white light, graceful and majestic, rebirth fire surrounding, rising from ashes, divine solar energy`,
    negativePrompt: NEGATIVE.character,
    tags: ['legendary', 'fire', 'immortal', 'rebirth'],
  },
  {
    id: 'char_titan_portrait',
    category: 'character',
    name: 'Ancient Titan',
    description: 'Primordial giant of creation',
    style: 'anime-portrait',
    size: { width: 512, height: 512 },
    prompt: `${STYLE.animePortrait}, ancient titan, massive stone-like body with glowing blue runes carved in skin, cosmic eyes showing galaxies, ancient wise face weathered by eons, mountain-sized presence implied, cosmic nebula background, primordial power`,
    negativePrompt: NEGATIVE.character,
    tags: ['legendary', 'earth', 'tank', 'ancient'],
  },
  {
    id: 'char_void_walker_portrait',
    category: 'character',
    name: 'Void Walker',
    description: 'Entity from between dimensions',
    style: 'anime-portrait',
    size: { width: 512, height: 512 },
    prompt: `${STYLE.animePortrait}, void walker, ethereal dark purple form with starfield within body, glowing white eyes like distant stars, reality warping around them, dimensional tears and portals, cosmic horror aesthetic but beautiful, unknowable presence`,
    negativePrompt: NEGATIVE.character,
    tags: ['legendary', 'void', 'teleport', 'cosmic'],
  },

  // JOKE/SPECIAL CHARACTERS
  {
    id: 'char_chef_portrait',
    category: 'character',
    name: 'Battle Chef',
    description: 'Culinary warrior extraordinaire',
    style: 'anime-portrait',
    size: { width: 512, height: 512 },
    prompt: `${STYLE.animePortrait}, battle chef, tall white chef hat and apron over armor, wielding giant frying pan as shield and cleaver as sword, determined cook expression, magical food buffs floating, kitchen fire background, absurdly epic`,
    negativePrompt: NEGATIVE.character,
    tags: ['joke', 'support', 'buffs', 'food'],
  },
  {
    id: 'char_chicken_portrait',
    category: 'character',
    name: 'Champion Chicken',
    description: 'The most unlikely hero',
    style: 'anime-portrait',
    size: { width: 512, height: 512 },
    prompt: `${STYLE.animePortrait}, heroic battle chicken, small chicken wearing tiny armor and helmet, fierce determined eyes, dramatic hero pose, feathers ruffled majestically, sunset behind, absurd but genuinely epic and inspiring`,
    negativePrompt: NEGATIVE.character,
    tags: ['joke', 'speed', 'critical', 'meme'],
  },

  // ============================================
  // CHARACTER SPRITES (256px chibi style)
  // ============================================
  {
    id: 'char_samurai_sprite',
    category: 'character',
    name: 'Samurai Sprite',
    description: 'Chibi samurai for gameplay',
    style: 'anime-chibi',
    size: { width: 256, height: 256 },
    prompt: `${STYLE.animeChibi}, samurai warrior, red and black armor, katana, topknot hair, cute determined face, idle standing pose, transparent background`,
    negativePrompt: NEGATIVE.character,
    tags: ['sprite', 'gameplay'],
  },
  {
    id: 'char_witch_sprite',
    category: 'character',
    name: 'Witch Sprite',
    description: 'Chibi witch for gameplay',
    style: 'anime-chibi',
    size: { width: 256, height: 256 },
    prompt: `${STYLE.animeChibi}, cute witch, purple robes, pointed hat, silver hair, magic wand, playful pose, transparent background`,
    negativePrompt: NEGATIVE.character,
    tags: ['sprite', 'gameplay'],
  },

  // ============================================
  // CHARACTER ICONS (64px pixel style)
  // ============================================
  {
    id: 'char_samurai_icon',
    category: 'character',
    name: 'Samurai Icon',
    description: 'HUD icon for samurai',
    style: 'pixel-icon',
    size: { width: 64, height: 64 },
    prompt: `${STYLE.pixelIcon}, samurai face, red helmet, fierce expression, transparent background`,
    negativePrompt: NEGATIVE.character,
    tags: ['icon', 'hud'],
  },

  // ============================================
  // MAGIC EFFECTS (various sizes)
  // ============================================
  {
    id: 'effect_fire_orb',
    category: 'effect',
    name: 'Fire Orb',
    description: 'Blazing fire projectile',
    style: 'vfx-painterly',
    size: { width: 128, height: 128 },
    prompt: `${STYLE.vfxPainterly}, fire orb spell, swirling orange and red flames, bright yellow core, ember particles, heat distortion, transparent background`,
    negativePrompt: NEGATIVE.effect,
    tags: ['projectile', 'fire', 'magic'],
  },
  {
    id: 'effect_ice_shard',
    category: 'effect',
    name: 'Ice Shard',
    description: 'Frozen crystal projectile',
    style: 'vfx-painterly',
    size: { width: 128, height: 128 },
    prompt: `${STYLE.vfxPainterly}, ice shard spell, crystalline blue ice spike, frost particles, cold mist trail, sparkling facets, transparent background`,
    negativePrompt: NEGATIVE.effect,
    tags: ['projectile', 'ice', 'magic'],
  },
  {
    id: 'effect_lightning_bolt',
    category: 'effect',
    name: 'Lightning Bolt',
    description: 'Electric discharge',
    style: 'vfx-painterly',
    size: { width: 256, height: 256 },
    prompt: `${STYLE.vfxPainterly}, lightning bolt spell, bright yellow electric arc, branching energy, spark particles, glowing core, transparent background`,
    negativePrompt: NEGATIVE.effect,
    tags: ['projectile', 'lightning', 'magic'],
  },
  {
    id: 'effect_heal_aura',
    category: 'effect',
    name: 'Healing Aura',
    description: 'Restorative magic circle',
    style: 'vfx-painterly',
    size: { width: 256, height: 256 },
    prompt: `${STYLE.vfxPainterly}, healing magic circle, soft green and white glow, leaf and nature particles, gentle sparkles, protective dome shape, transparent background`,
    negativePrompt: NEGATIVE.effect,
    tags: ['aoe', 'heal', 'support'],
  },
  {
    id: 'effect_dark_nova',
    category: 'effect',
    name: 'Dark Nova',
    description: 'Expanding void explosion',
    style: 'vfx-painterly',
    size: { width: 512, height: 512 },
    prompt: `${STYLE.vfxPainterly}, dark nova explosion, purple and black void energy expanding, reality cracks, soul particles being pulled in, cosmic horror aesthetic, transparent background`,
    negativePrompt: NEGATIVE.effect,
    tags: ['aoe', 'dark', 'damage'],
  },

  // ============================================
  // ITEMS (64-128px)
  // ============================================
  {
    id: 'item_health_potion',
    category: 'item',
    name: 'Health Potion',
    description: 'Red healing elixir',
    style: 'medieval-topdown',
    size: { width: 64, height: 64 },
    prompt: `${STYLE.medievalTopdown}, health potion bottle, red glowing liquid, heart-shaped bottle, golden stopper, magical sparkles, transparent background`,
    negativePrompt: NEGATIVE.terrain,
    tags: ['consumable', 'healing'],
  },
  {
    id: 'item_mana_potion',
    category: 'item',
    name: 'Mana Potion',
    description: 'Blue magic elixir',
    style: 'medieval-topdown',
    size: { width: 64, height: 64 },
    prompt: `${STYLE.medievalTopdown}, mana potion bottle, blue glowing liquid, star-shaped bottle, silver stopper, magical sparkles, transparent background`,
    negativePrompt: NEGATIVE.terrain,
    tags: ['consumable', 'mana'],
  },
  {
    id: 'item_gold_coin',
    category: 'item',
    name: 'Gold Coin',
    description: 'Currency gold piece',
    style: 'medieval-topdown',
    size: { width: 64, height: 64 },
    prompt: `${STYLE.medievalTopdown}, gold coin, shiny golden surface, crown emblem, stacked coins, metallic gleam, transparent background`,
    negativePrompt: NEGATIVE.terrain,
    tags: ['currency', 'loot'],
  },
  {
    id: 'item_chest',
    category: 'item',
    name: 'Treasure Chest',
    description: 'Wooden loot chest',
    style: 'medieval-topdown',
    size: { width: 96, height: 96 },
    prompt: `${STYLE.medievalTopdown}, treasure chest top-down view, wooden chest with golden metal bands, glowing keyhole, mysterious light emanating from cracks, transparent background`,
    negativePrompt: NEGATIVE.terrain,
    tags: ['container', 'loot', 'rare'],
  },

  // ============================================
  // MOUNTS (128-256px)
  // ============================================
  {
    id: 'mount_horse',
    category: 'mount',
    name: 'War Horse',
    description: 'Armored battle steed',
    style: 'medieval-topdown',
    size: { width: 128, height: 128 },
    prompt: `${STYLE.medievalTopdown}, war horse top-down view, brown stallion with metal armor barding, flowing mane, strong muscular build, battle-ready stance, transparent background`,
    negativePrompt: NEGATIVE.terrain,
    tags: ['mount', 'speed', 'common'],
  },
  {
    id: 'mount_dragon',
    category: 'mount',
    name: 'Drake',
    description: 'Fire-breathing dragon mount',
    style: 'medieval-topdown',
    size: { width: 256, height: 256 },
    prompt: `${STYLE.medievalTopdown}, dragon mount top-down view, red scaled wyrm with spread wings, glowing eyes, smoke from nostrils, powerful clawed limbs, transparent background`,
    negativePrompt: NEGATIVE.terrain,
    tags: ['mount', 'flying', 'legendary'],
  },

  // ============================================
  // ENEMIES (64-256px)
  // ============================================
  {
    id: 'enemy_swarm',
    category: 'enemy',
    name: 'Swarm Creature',
    description: 'Fast weak enemy in groups',
    style: 'medieval-topdown',
    size: { width: 64, height: 64 },
    prompt: `${STYLE.medievalTopdown}, small goblin creature top-down view, green skin, ragged clothes, crude dagger, hunched aggressive pose, transparent background`,
    negativePrompt: NEGATIVE.terrain,
    tags: ['enemy', 'swarm', 'weak'],
  },
  {
    id: 'enemy_tank',
    category: 'enemy',
    name: 'Tank Brute',
    description: 'Slow heavy armored enemy',
    style: 'medieval-topdown',
    size: { width: 128, height: 128 },
    prompt: `${STYLE.medievalTopdown}, armored ogre top-down view, massive body in plate armor, huge mace weapon, skull helmet, imposing presence, transparent background`,
    negativePrompt: NEGATIVE.terrain,
    tags: ['enemy', 'tank', 'strong'],
  },
  {
    id: 'enemy_boss_drake',
    category: 'enemy',
    name: 'Boss Drake',
    description: 'Massive dragon boss enemy',
    style: 'medieval-topdown',
    size: { width: 256, height: 256 },
    prompt: `${STYLE.medievalTopdown}, ancient dragon boss top-down view, massive black and red scaled body, four legs and huge wings, glowing fire in chest, terrifying presence, boss enemy, transparent background`,
    negativePrompt: NEGATIVE.terrain,
    tags: ['enemy', 'boss', 'dragon'],
  },
];

// Generate full prompt list for all characters
const ALL_CHARACTER_IDS = [
  'samurai', 'witch', 'ninja', 'paladin', 'necromancer', 'bard', 'druid',
  'fire_samurai', 'ice_witch', 'storm_ninja', 'shadow_paladin', 'earth_druid', 'light_bard', 'water_necro', 'wind_ninja',
  'dragon_knight', 'vampire', 'werewolf', 'slime', 'angel', 'demon', 'skeleton', 'ghost_player', 'minotaur', 'harpy_player', 'golem', 'lich',
  'dark_paladin', 'blood_necro', 'war_bard', 'shadow_ninja', 'holy_druid', 'plague_witch', 'arcane_samurai', 'wild_druid', 'stone_paladin', 'blade_dancer',
  'chef', 'mime', 'merchant', 'scarecrow', 'chicken',
  'phoenix', 'titan', 'void_walker', 'time_keeper', 'world_eater'
];

// Character descriptions for generating prompts
export const CHARACTER_LORE: Record<string, { name: string; title: string; element: string; description: string; visual: string }> = {
  samurai: { name: 'Samurai', title: 'Blade of Honor', element: 'fire', description: 'Honorable warrior mastering the way of the sword', visual: 'red and black yoroi armor, katana, topknot, battle-worn noble face' },
  witch: { name: 'Witch', title: 'Mistress of Mysteries', element: 'arcane', description: 'Ancient sorceress wielding forbidden magic', visual: 'purple robes with stars, pointed hat, silver hair, mystical purple eyes' },
  ninja: { name: 'Ninja', title: 'Shadow Walker', element: 'shadow', description: 'Silent assassin striking from darkness', visual: 'black shinobi outfit, face mask, sharp eyes, kunai weapons' },
  paladin: { name: 'Paladin', title: 'Divine Champion', element: 'light', description: 'Holy knight blessed by the gods', visual: 'golden plate armor, white tabard with sun, blonde hair, holy light' },
  necromancer: { name: 'Necromancer', title: 'Death Whisperer', element: 'dark', description: 'Master of undeath and soul magic', visual: 'black tattered robes, skull motifs, pale skin, glowing purple eyes' },
  bard: { name: 'Bard', title: 'Voice of Legends', element: 'sonic', description: 'Charismatic performer with magical music', visual: 'colorful renaissance outfit, feathered cap, lute, charming smile' },
  druid: { name: 'Druid', title: 'Nature\'s Guardian', element: 'nature', description: 'Protector of the wild with shapeshifting powers', visual: 'green robes with vines, antler headdress, wooden staff, wise eyes' },
  fire_samurai: { name: 'Fire Samurai', title: 'Inferno Blade', element: 'fire', description: 'Warrior possessed by a flame spirit', visual: 'burning red armor wreathed in flames, fire katana, wild flame hair' },
  ice_witch: { name: 'Ice Witch', title: 'Frost Queen', element: 'ice', description: 'Sorceress of eternal winter', visual: 'crystalline blue robes, ice crown, pale blue skin, frozen beauty' },
  storm_ninja: { name: 'Storm Ninja', title: 'Lightning Strike', element: 'lightning', description: 'Assassin faster than lightning', visual: 'electric blue outfit, white static hair, lightning kunai, electric eyes' },
  shadow_paladin: { name: 'Shadow Paladin', title: 'Dark Crusader', element: 'dark', description: 'Holy knight corrupted by shadow', visual: 'black armor with purple glow, dark cape, haunted eyes, void energy' },
  earth_druid: { name: 'Earth Druid', title: 'Stone Shaper', element: 'earth', description: 'One with the living stone', visual: 'brown and green robes, rock-like skin patches, crystal staff, ancient' },
  light_bard: { name: 'Light Bard', title: 'Sunsingers Grace', element: 'light', description: 'Blessed performer channeling divine music', visual: 'golden white outfit, harp of light, glowing aura, angelic beauty' },
  water_necro: { name: 'Water Necromancer', title: 'Drowned One', element: 'water', description: 'Commands spirits of the drowned', visual: 'waterlogged robes, seaweed crown, ghostly blue skin, dripping' },
  wind_ninja: { name: 'Wind Ninja', title: 'Gale Dancer', element: 'wind', description: 'Moves like the wind itself', visual: 'light flowing outfit, wind-swept hair, translucent form, serene' },
  dragon_knight: { name: 'Dragon Knight', title: 'Wyrm Sworn', element: 'fire', description: 'Warrior bonded with dragon blood', visual: 'draconic scale armor, dragon horns, reptilian eyes, wings' },
  vampire: { name: 'Vampire Lord', title: 'Crimson Noble', element: 'dark', description: 'Ancient bloodthirsty aristocrat', visual: 'gothic black and red attire, pale skin, red eyes, fangs' },
  werewolf: { name: 'Werewolf', title: 'Moon Cursed', element: 'nature', description: 'Hybrid beast of terrible power', visual: 'half-transformed, fur and fangs, torn clothes, feral yellow eyes' },
  slime: { name: 'Slime', title: 'Goo Guardian', element: 'water', description: 'Surprisingly heroic blob creature', visual: 'translucent blue gel body, cute face, wobbling form' },
  angel: { name: 'Angel', title: 'Celestial Herald', element: 'light', description: 'Divine warrior from the heavens', visual: 'white feathered wings, golden armor, halo, pure white eyes' },
  demon: { name: 'Demon', title: 'Infernal Terror', element: 'fire', description: 'Fiend from the burning hells', visual: 'red skin, curved horns, bat wings, burning eyes, fanged grin' },
  skeleton: { name: 'Skeleton', title: 'Bone Warrior', element: 'dark', description: 'Undead fighter with unbreaking will', visual: 'animated bones, rusty armor pieces, glowing eye sockets' },
  ghost_player: { name: 'Ghost', title: 'Spectral Wanderer', element: 'dark', description: 'Spirit unable to pass on', visual: 'translucent ethereal form, trailing wisps, sad glowing eyes' },
  minotaur: { name: 'Minotaur', title: 'Labyrinth Guardian', element: 'earth', description: 'Bull-headed beast of great strength', visual: 'massive bull head, muscular body, bronze armor, great axe' },
  harpy_player: { name: 'Harpy', title: 'Sky Hunter', element: 'wind', description: 'Bird-woman with deadly talons', visual: 'feathered wings and legs, human torso, sharp talons, fierce beauty' },
  golem: { name: 'Golem', title: 'Construct Awakened', element: 'earth', description: 'Magical construct given life', visual: 'stone body with glowing runes, heavy limbs, crystal core' },
  lich: { name: 'Lich', title: 'Deathless Mage', element: 'dark', description: 'Necromancer who conquered death', visual: 'skeletal face, royal dark robes, soul phylactery, crown of bones' },
  dark_paladin: { name: 'Dark Paladin', title: 'Fallen Grace', element: 'dark', description: 'Holy knight who embraced darkness', visual: 'corrupted black armor, unholy symbols, pale face, void aura' },
  blood_necro: { name: 'Blood Necromancer', title: 'Sanguine Master', element: 'dark', description: 'Commands blood and life force', visual: 'crimson stained robes, blood magic swirling, pale vampire-like' },
  war_bard: { name: 'War Bard', title: 'Battle Hymn', element: 'sonic', description: 'Inspires armies with war songs', visual: 'armored performer, war drums, rallying pose, fierce expression' },
  shadow_ninja: { name: 'Shadow Ninja', title: 'Void Assassin', element: 'dark', description: 'Merged with living shadow', visual: 'barely visible dark form, shadow tendrils, only eyes visible' },
  holy_druid: { name: 'Holy Druid', title: 'Natures Blessing', element: 'light', description: 'Divine nature magic combined', visual: 'golden and green robes, radiant antlers, holy light and vines' },
  plague_witch: { name: 'Plague Witch', title: 'Disease Bearer', element: 'poison', description: 'Spreads sickness and decay', visual: 'sickly green robes, bubbling potions, pallid skin, toxic aura' },
  arcane_samurai: { name: 'Arcane Samurai', title: 'Spell Blade', element: 'arcane', description: 'Warrior combining magic and steel', visual: 'purple glowing armor, rune-covered katana, mystic symbols' },
  wild_druid: { name: 'Wild Druid', title: 'Feral Heart', element: 'nature', description: 'More beast than human', visual: 'partially transformed, wild hair, feral eyes, primal markings' },
  stone_paladin: { name: 'Stone Paladin', title: 'Unbreaking Wall', element: 'earth', description: 'Immovable defender of the weak', visual: 'massive stone-like armor, tower shield, stoic face' },
  blade_dancer: { name: 'Blade Dancer', title: 'Dancing Death', element: 'physical', description: 'Fighter who moves like art', visual: 'flowing silks and armor combo, twin swords, graceful pose' },
  chef: { name: 'Battle Chef', title: 'Culinary Combat', element: 'fire', description: 'Weaponized cooking mastery', visual: 'chef hat and apron over armor, frying pan shield, cleaver' },
  mime: { name: 'Mime', title: 'Silent Performance', element: 'arcane', description: 'Creates reality through pantomime', visual: 'black and white outfit, white face paint, invisible objects' },
  merchant: { name: 'Merchant', title: 'Golden Tongue', element: 'physical', description: 'Money is the best weapon', visual: 'expensive robes, coin purses, calculating eyes, gold everywhere' },
  scarecrow: { name: 'Scarecrow', title: 'Field Terror', element: 'dark', description: 'Animated protector of crops', visual: 'straw body, tattered clothes, button eyes, creepy but heroic' },
  chicken: { name: 'Champion Chicken', title: 'Unlikely Hero', element: 'physical', description: 'The most absurd warrior', visual: 'tiny chicken in miniature armor, fierce determined eyes, epic' },
  phoenix: { name: 'Phoenix', title: 'Eternal Flame', element: 'fire', description: 'Immortal bird of rebirth', visual: 'humanoid of golden flames, feathered fire wings, reborn radiance' },
  titan: { name: 'Titan', title: 'Primordial Giant', element: 'earth', description: 'Being from the dawn of creation', visual: 'massive stone body, cosmic runes, galaxy eyes, ancient power' },
  void_walker: { name: 'Void Walker', title: 'Between Worlds', element: 'void', description: 'Entity from dimensional gaps', visual: 'dark form with starfield within, reality tears, cosmic horror beauty' },
  time_keeper: { name: 'Time Keeper', title: 'Chrono Guardian', element: 'arcane', description: 'Controller of temporal flow', visual: 'clockwork robes, pocket watches everywhere, ageless face, time distortion' },
  world_eater: { name: 'World Eater', title: 'The End', element: 'void', description: 'Cosmic entity that consumes reality', visual: 'massive dark void form, consuming everything, terrifying majesty' },
};

export default ART_PROMPTS;
